
##canalµƒøÕªß∂À≈‰÷√
canal:
  conf:
    batchSize: 2000
    syncBatchSize: 1000
    retries: 0
    timeout:
    canalServerHost:
    destination: example
    zookeeperHosts: localhost:2181
    username:
    password:
server:
  port: 8080

#jdbc:mysql://172.31.0.53:3307   ssb@2017
#jdbc:mysql://127.0.0.1:3306
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/ibtool?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  profiles:
    active: dev